- name: set up ros keys
  apt_key:
    keyserver: ha.pool.sks-keyservers.net
    id: '0xab17c654'
- name: accept software from packages.ros.org
  apt_repository:
    repo: 'deb http://packages.ros.org/ros/ubuntu {{ ansible_lsb.codename }} main'
    filename: 'ros-latest'
    update_cache: yes
- name: install ros packages
  apt:
    pkg: "{{ ros_packages | map('regex_replace', '(.*)', 'ros-'+ros_versions[ansible_lsb.codename]+'-\\1') | list }}"
